### ISSUE TITLE
Extremely slow performance on mounted volumes

### ISSUE THREAD

**Issue by rahulbreddy** [Azure/kubernetes-volume-drivers#10]
I followed the readme instructions and created a PV and PVC. The volume seems to be mouting but not before at least one timeout event.

Once everything is up and running, trying to list the contents of the data directory takes a very long time (in minutes) eventually returning 0 items though I have 1 non-empty blob in my container.

Also, echo "foo" > test.txt in the data directory results in an I/O error after several minutes.

I verified the logs on the node for errors but did not find any. Both the container and the cluster are in the same region and the cache directory is on a ramdisk.

Any ideas/thoughts on what might be going wrong here or any tips on what I could do to investigate this further?

**Comment by andyzhangx** [comment]
@rahulbreddy so you are experiencing slow perf using blobfuse driver now, right? could it reproable? what's the detailed steps?
cc @seguler

**Comment by rahulbreddy** [comment]
@andyzhangx I did the following on our AKS cluster:

- kubectl create -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml
- kubectl create secret generic blobfusecreds --from-literal accountname=ACCOUNT-NAME --from-literal accountkey="ACCOUNT-KEY" --type="azure/blobfuse"
- wget https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/blobfuse/pv-blobfuse-flexvol.yaml
- vi pv-blobfuse-flexvol.yaml - changed the container name in this step
- kubectl create -f pv-blobfuse-flexvol.yaml
- kubectl create -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/blobfuse/pvc-blobfuse-flexvol.yaml
- kubectl create -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/blobfuse/nginx-flex-blobfuse-pvc.yaml
- kubectl describe po nginx-flex-blobfuse
- Wait for the pod state to be running
- In the Events section I see the below:
> Warning  FailedMount  4m6s (x2 over 6m24s)  kubelet, aks-agentpool-<a_number>-2  Unable to mount volumes for pod "nginx-flex-blobfuse_xxx(an_uuid)": timeout expired waiting for volumes to attach or mount for pod "xxx"/"nginx-flex-blobfuse". list of unmounted volumes=[flexvol-mount]. list of unattached volumes=[flexvol-mount default-token-xxxxx]
- kubectl exec -it nginx-flex-blobfuse -- bash
- df -h shows that the data directory exists
> blobfuse         30G   12G   18G  39% /data
- `ls /data` returns 0 items after several minutes though my container has a non-empty blob
- `echo "foo" > test.txt` fails after several minutes with an I/O error. No specific details in the error.

I see a similar behavior in the mount path on the node. To rule out other communication issues, I tired to download the file directly using curl in the nginx-flex-blobfuse pod and that seems to download fine.
I am awaiting access to the node to try curl download file from it just to be sure.

**Comment by rahulbreddy** [comment]
@andyzhangx A small correction from one on the previous posts. The cache is on an SSD and not ramdisk.

**Comment by rahulbreddy** [comment]
@andyzhangx @seguler Did you guys get a chance to review the above information?

**Comment by andyzhangx** [comment]
@rahulbreddy to narrow down the issue, could you ssh to that node and by running `mount | grep blobfuse`, you could find that mounted dir directly, and then check whether that dir is accessible on your node.

**Comment by andyzhangx** [comment]
hi @rahulbreddy do you have chance to repro this issue? To narrow down the issue, you could use `blobfuse` command directly on that agent VM, e.g.
```
/usr/bin/blobfuse /mntpoint --container-name=nginx --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
```

And then check whethter there is timeout.
Pls make sure your VM and storage account are in the same region.

**Comment by rahulbreddy** [comment]
Hi @andyzhangx I did not get a chance to investigate this further. Given the future direction we were heading towards, it made more sense for us to use the blob SDK/APIs. We can close this issue for now. I will reopen the issue if I get a chance to try this again in the future.
