### ISSUE TITLE
secrets "blobfusecreds" not found

### ISSUE THREAD

**Issue by fboylu** [Azure/kubernetes-volume-drivers#11]
I am getting the following from the container which is stuck in creating stage. Where does these secrets get stored? 

Warning  FailedMount  35s (x23 over 31m)    kubelet, aks-nodepool1-17354647-1  MountVolume.SetUp failed for volume "blob" : Couldn't get secret kubeflow/blobfusecreds err: secrets "blobfusecreds" not found

any ideas what may be wrong?
thanks

**Comment by andyzhangx** [comment]
pls use `azure/blobfuse` in `type` parameter instead:
```
kubectl create secret generic blobfusecreds --from-literal accountname=ACCOUNT-NAME --from-literal accountkey="ACCOUNT-KEY" --type="azure/blobfuse"
```

**Comment by fboylu** [comment]
that is exactly what I used :
kubectl create secret generic blobfusecreds --from-literal accountname=$STORAGE_ACCOUNT_NAME --from-literal accountkey=$STORAGE_ACCOUNT_KEY --type="azure/blobfuse"

**Comment by andyzhangx** [comment]
I see, your workloads are in `kubeflow` namespace, could you edit your pod spec like following:
```
      secretRef:
        name: blobfusecreds
        namespace: default
```

Or you could create secret under `kubeflow` namespace:
```
kubectl create secret generic blobfusecreds --from-literal accountname=$STORAGE_ACCOUNT_NAME --from-literal accountkey=$STORAGE_ACCOUNT_KEY --type="azure/blobfuse" --namespace=kubeflow
```

**Comment by fboylu** [comment]
it worked, thank you!
