### ISSUE TITLE
NVMe disk was not discovered on Standard_L8s_v2 VM SKU 

### ISSUE THREAD

**Issue by sunkararp** [Azure/kubernetes-volume-drivers#113]
**What happened**:
I'm using Standard_L8s_v2 VM SKU 
- The 1X1.92 TM nvme disk was not discovered on
- It only discovered 80 GB temp disk

**What you expected to happen**:
Both 80 GB temp disk and 1.92 NVMe disk be discovered

**How to reproduce it**:
Create a K8s Cluster with vm scale set with Standard_L8s_v2 VM SKU 

**Anything else we need to know?**:
- Followed instructions from this https://github.com/Azure/kubernetes-volume-drivers/tree/master/local
- This is working fine with other node pools in our ASK cluster
- Screen capture
<img width="1531" alt="Capture" src="https://user-images.githubusercontent.com/10903166/150248947-fdb323da-6305-490b-b7ec-46bb7564a498.PNG">

**Environment**:
- Kubernetes version (use `kubectl version`): v1.20.7
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
have you used `https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/local/local-pv-provisioner-nvmedisk.yaml`? it would find `/dev/nvm*` disks on agent node.

**Comment by sunkararp** [comment]
@andyzhangx thanks for the reply.

- I did use https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/local/local-pv-provisioner-nvmedisk.yaml? 
- Did did not find the NVMe disks
- Surprisingly, I have few other node pools that use Standard_L8s_v2 VM SKU and work fine

**Comment by andyzhangx** [comment]
@sunkararp could you ssh to the agent node, and check whether there is `/dev/nvm*` device? if there is, follow guide here to get logs: https://github.com/Azure/kubernetes-volume-drivers/tree/master/local#troubleshooting

**Comment by andyzhangx** [comment]
and did you add any taint to prevent that daemonset run on your node pool?

**Comment by andyzhangx** [comment]
so there is no `/dev/nvm*` disk under that node?

**Comment by sunkararp** [comment]
> and did you add any taint to prevent that daemonset run on your node pool?

No

**Comment by andyzhangx** [comment]
then do you know what's the device name of that nvme disk in that node pool? It should be `/dev/nvme*` device name for all nvme disks. Is it reproable?

**Comment by sunkararp** [comment]
Just noticed...
- we were using mcr.microsoft.com/k8s/local-volume-provisioner:v2.3.5-alpha of local-volume-provisioner
- New script is using mcr.microsoft.com/k8s/local-volume-provisioner:v2.4.0
- Does this matter?

**Comment by andyzhangx** [comment]
> Just noticed...
> 
> * we were using mcr.microsoft.com/k8s/local-volume-provisioner:v2.3.5-alpha of local-volume-provisioner
> * New script is using mcr.microsoft.com/k8s/local-volume-provisioner:v2.4.0
> * Does this matter?

@sunkararp these 2 versions almost has no difference. I think you need to find out what is the nvme device on that node, it's strange.

**Comment by sunkararp** [comment]
> @sunkararp these 2 versions almost has no difference. I think you need to find out what is the nvme device on that node, it's strange.

How do I do that? I cannot connect to the node due to compliance.

I can run kubectl exec -it POD however.

**Comment by sunkararp** [comment]
BTW does app container deployed on this VM need to do anything for nvme disks to be visible?

**Comment by andyzhangx** [comment]
try `kubectl exec -it local-volume-provisioner-xxxxx -n kube-system -- ls /dev/`

**Comment by sunkararp** [comment]
<img width="1292" alt="Capture" src="https://user-images.githubusercontent.com/10903166/150263993-038309b7-0ea2-4ea1-96ca-04ecb36142b6.PNG">

**Comment by andyzhangx** [comment]
i see nvme disk is there, there is conflict between `https://github.com/Azure/kubernetes-volume-drivers/blob/master/local/local-pv-provisioner-tempdisk.yaml` and `local-pv-provisioner-nvmedisk.yaml`, pls only use one yaml config.

**Comment by sunkararp** [comment]
Awesome!
Thanks for your help

**Comment by sunkararp** [comment]
Sorry to reopen this issue.
- I changed access mode to ReadWriteMany & it fails to BIND (I recreated the VM)
- Below is the screen capture of the logs
  <img width="1230" alt="Capture" src="https://user-images.githubusercontent.com/10903166/151666049-a5b94158-68e6-4f6a-ab73-8eb488580351.PNG">

Therefore, is ReadWriteMany supported?

**Comment by andyzhangx** [comment]
@sunkararp no, local disk only supports ReadWriteOnce

**Comment by sunkararp** [comment]
thanks, for quick reply

**Comment by olsenme** [comment]
@sunkararp would you be willing to have a chat with the PG team on your use case for this?

**Comment by sunkararp** [comment]
> @sunkararp would you be willing to have a chat with the PG team on your use case for this?

Sure. 

BTW, we already in contact with MSFT on another issue relating to NVMe disk. TrackingID#2207130010002328
