### ISSUE TITLE
MountVolume.SetUp failed for volume "pv-blobfuse-flexvol" : invalid character 'F' looking for beginning of value

### ISSUE THREAD

**Issue by t1agob** [Azure/kubernetes-volume-drivers#12]
Hello,
I followed all the instructions from the readme document and it fails with one of the error message types listed in it.

**_MountVolume.SetUp failed for volume "pv-blobfuse-flexvol" : invalid character 'F' looking for beginning of value_**

I have connected to one of the nodes of the cluster and in the log file this is the message:

**_Fri Jan 25 14:57:50 UTC 2019 INFO: {"status": "Success", "capabilities": {"attach": false}}_**

Can you help? Thanks!

**Comment by andyzhangx** [comment]
could you provide `/var/log/blobfuse-driver.log`? you may remove the secret info before pasting. thanks.

**Comment by t1agob** [comment]
Hello @andyzhangx ,
on **node-0** the `/var/log/blobfuse-driver.log` log just shows:

> Fri Jan 25 14:57:50 UTC 2019 INFO: {"status": "Success", "capabilities": {"attach": false}}

On **node-1** the log shows: _(lines are getting striked-out due to "~" characther)_

> Fri Jan 25 15:02:15 UTC 2019 INFO: {"status": "Success", "capabilities": {"attach": false}}
> Fri Jan 25 15:04:10 UTC 2019 EXEC: mkdir -p /var/lib/kubelet/pods/7803c3d2-20b2-11e9-8fed-16014ecf7145/volumes/azure~blobfuse/pv-blobfuse-flexvol
> Fri Jan 25 15:04:10 UTC 2019 INF: export storage account - export AZURE_STORAGE_ACCOUNT=ftascribetech AZURE_STORAGE_ACCESS_KEY=...
> Fri Jan 25 15:04:10 UTC 2019 EXEC: /usr/bin/blobfuse /var/lib/kubelet/pods/7803c3d2-20b2-11e9-8fed-16014ecf7145/volumes/azure~blobfuse/pv-blobfuse-flexvol --container-name=nginx --tmp-path=/tmp/blobfuse -o allow_other  --file-cache-timeout-in-seconds=120
> Fri Jan 25 15:04:10 UTC 2019 ERROR: { "status": "Failure", "message": "Failed to mount device /dev/ at /var/lib/kubelet/pods/7803c3d2-20b2-11e9-8fed-16014ecf7145/volumes/azure~blobfuse/pv-blobfuse-flexvol, accountname:ftascribetech, error log:Fri Jan 25 15:04:10 UTC 2019 EXEC: /usr/bin/blobfuse /var/lib/kubelet/pods/7803c3d2-20b2-11e9-8fed-16014ecf7145/volumes/azure~blobfuse/pv-blobfuse-flexvol --container-name=nginx --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120" }
> Fri Jan 25 15:04:11 UTC 2019 EXEC: mkdir -p /var/lib/kubelet/pods/7803c3d2-20b2-11e9-8fed-16014ecf7145/volumes/azure~blobfuse/pv-blobfuse-flexvol
> Fri Jan 25 15:04:11 UTC 2019 INF: export storage account - export AZURE_STORAGE_ACCOUNT=ftascribetech AZURE_STORAGE_ACCESS_KEY=...
> Fri Jan 25 15:04:11 UTC 2019 EXEC: /usr/bin/blobfuse /var/lib/kubelet/pods/7803c3d2-20b2-11e9-8fed-16014ecf7145/volumes/azure~blobfuse/pv-blobfuse-flexvol --container-name=nginx --tmp-path=/tmp/blobfuse -o allow_other  --file-cache-timeout-in-seconds=120
....

and the last log entry gets repeated every 120s.

**PS:** I haven't removed any secret from the file. AZURE_STORAGE_ACCESS_KEY shows "..." already in the log file.

**Comment by t1agob** [comment]
Thanks for your help @andyzhangx. I was able to make it work when connected to node-1 so I read the article again and saw I missed one of the requirements: **a container**.

I was assuming it would create one for me. Thanks so much for your help and sorry for the trouble.
