### ISSUE TITLE
[BUG] Blobfuse cannot mount folder to AKS pod

### ISSUE THREAD

**Issue by win5923** [Azure/kubernetes-volume-drivers#143]
**Describe the bug**
When using PVC (Persistent Volume Claim) to bind Azure Blob, I noticed that only files in the current directory are mounted into the pod, while folders are not.

**Expected behavior**
The data inside the folder should also be mountable into the pod.

**Screenshots**
Azure blob:
![image](https://github.com/Azure/AKS/assets/56353753/0a717a3e-faca-4a12-a715-4a1085364eea)

pod:
![image](https://github.com/Azure/AKS/assets/56353753/b19745f3-6b06-440b-80da-99e8d6a32b6a)

**Environment (please complete the following information):**
 - Kubernetes version: 1.28.5

**Additional context**
azure storage account information:
![image](https://github.com/Azure/AKS/assets/56353753/81e9759b-a29c-4c65-ae4c-88e44ff8c8c2)

**Comment by andyzhangx** [comment]
blobfuse flexvolume plugin is already deprecated, pls use blob csi driver instead: https://learn.microsoft.com/en-us/azure/aks/azure-blob-csi?tabs=NFS

**Comment by win5923** [comment]
> blobfuse flexvolume plugin is already deprecated, pls use blob csi driver instead: https://learn.microsoft.com/en-us/azure/aks/azure-blob-csi?tabs=NFS

I am using the azure blob csi currently.

**Comment by andyzhangx** [comment]
pls check comments here: https://github.com/Azure/AKS/issues/4274#issuecomment-2102486680
