### ISSUE TITLE
Dynamic volume provisioning?

### ISSUE THREAD

**Issue by DougDavenport** [Azure/kubernetes-volume-drivers#20]
Does the smb flexvolume driver support this:

https://kubernetes.io/docs/concepts/storage/dynamic-provisioning/

If so then can you please show an example.

**Comment by andyzhangx** [comment]
@DougDavenport of course not, it only supports static provisioning, that is user must provide a SMB server in advance. And azure file plugin supports Dynamic volume provisioning

**Comment by DougDavenport** [comment]
Thank you
