### ISSUE TITLE
[Document Improvement Request] Add requirements to dysk driver

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/kubernetes-volume-drivers#24]
**What happened**:
The dysk driver requires the non-HTTPS (HTTP) access to the storage account.
The storage account created by AKS disabled HTTP access by default.

**What you expected to happen**:
Could you add this requirement to the doc?
https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/dysk

**How to reproduce it**:
Always when using the storage account created by AKS.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
AKS: kubernetes 1.12.7
- OS (e.g. from /etc/os-release):
might be Ubuntu (managed by AKS)
- Kernel (e.g. `uname -a`):
- Install tools:
AKS
- Others:

**Comment by andyzhangx** [comment]
close this issue since `dysk` driver is deprecated
