### ISSUE TITLE
[dysk] Add support to automatic creation of empty VHD for dysk

### ISSUE THREAD

**Issue by tanaka-takayoshi** [Azure/kubernetes-volume-drivers#25]
**Is your feature request related to a problem?/Why is this needed**
The current dysk driver requires the VHD file exists beforehand.
Though I need just an empty VHD file, it's too messy to create an empty VHD file.
This is also an Azure side issue, but it seems Azure doesn't intend to support it.
https://github.com/Azure/azure-cli/issues/655

**Describe the solution you'd like in detail**
The dysk driver supports creating an empty VHD when `blob` filed is empty.

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
close this since dysk driver is deprecated
