### ISSUE TITLE
Support blobfuse custom storage endpoint

### ISSUE THREAD

**Issue by ewyuanzhang** [Azure/kubernetes-volume-drivers#28]
I am trying to use this with Azure in China, but I cannot modify the storage endpoint as described [here](https://github.com/Azure/azure-storage-fuse/pull/85) in Blobfuse. Do you consider adding the support of custom storage endpint?

**Comment by andyzhangx** [comment]
I submitted a PR in blobfuse repo: https://github.com/Azure/azure-storage-fuse/pull/281
It's better add env support for custom storage endpoint

**Comment by andyzhangx** [comment]
cc @seguler

**Comment by andyzhangx** [comment]
fixed by https://github.com/Azure/kubernetes-volume-drivers/pull/42 on `mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.11`
