### ISSUE TITLE
can't run the example given

### ISSUE THREAD

**Issue by cometta** [Azure/kubernetes-volume-drivers#31]
**What happened**:
I run the option 1 example and get below error

vents:
  Type     Reason       Age                From                               Message
  ----     ------       ----               ----                               -------
  Normal   Scheduled    31s                default-scheduler                  Successfully assigned default/nginx-flex-blobfuse to aks-nodepool1-31835897-0
  Warning  FailedMount  14s (x6 over 31s)  kubelet, aks-nodepool1-31835897-0  MountVolume.SetUp failed for volume "test" : invalid character 'F' looking for beginning of value

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.3", GitCommit:"5e53fd6bc17c0dec8434817e69b04a25d8ae0ff0", GitTreeState:"clean", BuildDate:"2019-06-06T01:44:30Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by andyzhangx** [comment]
could you attach the `/var/log/blobfuse-driver.log` file on the agent node? Thanks.

**Comment by cometta** [comment]
@andyzhangx , elaborate more please, is agent node is the pod running blobfuse-flexvol ?

> kubectl logs -f blobfuse-flexvol-installer-gvtrt --namespace kube-system
install done, daemonset sleeping

when i run the pod/nginx-flex-blobfuse example, the status remain as ContainerCreating and log showing MountVolume.SetUp failed for volume "test" : invalid character 'F' looking for beginning of value

**Comment by andyzhangx** [comment]
@cometta You need to ssh to that agent node, and get the log file `/var/log/blobfuse-driver.log`

**Comment by cometta** [comment]
@andyzhangx 

`
Sat Aug  3 03:04:06 UTC 2019 EXEC: mkdir -p /var/lib/kubelet/pods/the_pod_hash_masked_privacy/volumes/azure~blobfuse/test
Sat Aug  3 03:04:06 UTC 2019 INF: AZURE_STORAGE_ACCESS_KEY is set
Sat Aug  3 03:04:06 UTC 2019 INF: export storage account - export AZURE_STORAGE_ACCOUNT=<masked_privacy>
Sat Aug  3 03:04:06 UTC 2019 EXEC: blobfuse /var/lib/kubelet/pods/the_pod_hash_masked_privacy/volumes/azure~blobfuse/test --container-name=CONTAINER-NAME --tmp-path=/tmp/blobfuse -o allow_other  --file-cache-timeout-in-seconds=120
Sat Aug 3 03:04:06 UTC 2019 ERROR: { "status": "Failure", "message": "Failed to mount device /dev/ at /var/lib/kubelet/pods/the_pod_hash_masked_privacy/volumes/azure~blobfuse/test, accountname:<masked_privacy>, error log:Sat Aug 3 03:04:06 UTC 2019 EXEC: blobfuse /var/lib/kubelet/pods/the_pod_hash_masked_privacy/volumes/azure~blobfuse/test --container-name=CONTAINER-NAME --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120" }

`

**Comment by andyzhangx** [comment]
@cometta Your error could be due to non-existing storage account or storage container, to narrow down this issue, could you run following command on that agent node to check whether blobfuse works:
```
export AZURE_STORAGE_ACCOUNT=
export AZURE_STORAGE_ACCESS_KEY=
blobfuse /var/lib/kubelet/pods/the_pod_hash_masked_privacy/volumes/azure~blobfuse/test --container-name=CONTAINER-NAME --tmp-path=/tmp/blobfuse -o allow_other --file-cache-timeout-in-seconds=120
```

**Comment by cometta** [comment]
my bad. Thank you for guiding on how to troubleshoot it. @andyzhangx . The reason was due to incorrect container name
