### ISSUE TITLE
SMB Driver cannot handle special characters in credentials

### ISSUE THREAD

**Issue by bbgobie** [Azure/kubernetes-volume-drivers#34]
**What happened**:
If you try and use a password with a special character like $ in it you will get a permission denied as the $ will evaluate instead of getting passed as part of the password.

**What you expected to happen**:
Successful cifs mount
**How to reproduce it**:
Create a SMB share with access with an account with a password like $somespecial!Stuff#
Mount SMB
**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.1", GitCommit:"4485c6f18cee9a5d3c3b4e523bd27972b1b53892", GitTreeState:"clean", BuildDate:"2019-07-18T09:18:22Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.7", GitCommit:"4683545293d792934a7a7e12f2cc47d20b2dd01b", GitTreeState:"clean", BuildDate:"2019-06-06T01:39:30Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

    Image:          mcr.microsoft.com/k8s/flexvolume/smb-flexvolume
    Image ID:       docker-pullable://mcr.microsoft.com/k8s/flexvolume/smb-flexvolume@sha256:570e6585d84735409b22487ea24dccda358321e79df722a25f6057d9e48812c3

**Comment by andyzhangx** [comment]
@bbgobie would you use `\$somespecial\!Stuff#` instead? `$!` does not work in `echo` command, you could verify your password parsing by running:
```
echo `\$somespecial\!Stuff#`
```
if `echo` command works well, then your password could be parsed in the smb plugin

**Comment by bbgobie** [comment]
This does work for me, thanks!
