### ISSUE TITLE
timeout expired waiting for volumes to attach or mount

### ISSUE THREAD

**Issue by omyno** [Azure/kubernetes-volume-drivers#38]
**What happened**:
Mounting manually on the host works fine.

Creating the example pod results in:

> Unable to mount volumes for pod "nginx-flex-smb_production-floor(4c94b5c5-f415-11e9-af76-d485646b06e2)": timeout expired waiting for volumes to attach or mount for pod "production-floor"/"nginx-flex-smb". list of unmounted volumes=[test]. list of unattached volumes=[test default-token-gn6d7]

`docker logs kubelet`:
> E1021 17:12:03.469239    2697 desired_state_of_world_populator.go:311] Failed to add volume "flexvol-mount" (specName: "pv-smb-flexvol") for pod "54a7abf0-f40e-11e9-aa6c-984be1008bfe" to desiredStateOfWorld. err=failed to get Plugin from volumeSpec for volume "pv-smb-fl
exvol" err=no volume plugin matched

**Environment**:
- Kubernetes version (use `kubectl version`): `Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.6", GitCommit:"96fac5cd13a5dc064f7d9f4f23030a6aeface6cc", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:16Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}`

- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.0.0-31
- Install tools: Rancher

**Comment by andyzhangx** [comment]
it said: `no volume plugin matched`

have you installed smb plugin by:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/smb#option1-automatically-install-by-k8s-daemonset

Note: You may replace /etc/kubernetes/volumeplugins with /usr/libexec/kubernetes/kubelet-plugins/volume/exec/(by default) in install-smb-flexvol-ubuntu.sh if it's not a Kubernetes cluster created by AKS or aks-engine

**Comment by omyno** [comment]
Thanks for your reply, replacing the directory for volumeplugins did the trick.
