### ISSUE TITLE
azure disks in different subscription

### ISSUE THREAD

**Issue by abelal83** [Azure/kubernetes-volume-drivers#39]
**Is your feature request related to a problem? Please describe.**
We have a requirement to charge back users of kubernetes resources, for storage we create disks in the users owened azure resource group using the method described here https://github.com/Azure/AKS/issues/873. However, not all the resource groups are in the same subscription as AKS so unable to get AKS to auto provision using a claim template. We instead having to manually create disks and mount them, not great at all.

**Describe the solution you'd like in detail**
I would like the disk driver to support provisioning disks in other subscriptions.

**Describe alternatives you've considered**
Manually creating disks and mounting them. Not ideal as we unable to scale out statefule sets without first creating disks.

**Comment by andyzhangx** [comment]
it's not supported, not in our road map, not sure whether ARM VM would support cross-subscription feature.

**Comment by abelal83** [comment]
That's a shame 🙁

MS provide various models for azure billing/organising, one being subscription per team. Without support for cross subscription resources, keeping track of costs has become too hard to manage. I appreciate there is no road map for this which does leave us in a difficult position. 

We've tried storage accounts but are extremely slow in comparison to disks. Are there any other alternatives?

**Comment by andyzhangx** [comment]
actually there is VHD disk on azure file solution: https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/deploy/example/disk, it's unmanaged disk solution, while for managed disk, we don't support cross-subs
