### ISSUE TITLE
AZURE_STORAGE_BLOB_ENDPOINT is not set/populated when calling blobfuse 

### ISSUE THREAD

**Issue by keerthiadu** [Azure/kubernetes-volume-drivers#41]
**Is your feature request related to a problem? Please describe.**
blobfuse now supports an environment variable [AZURE_STORAGE_BLOB_ENDPOINT ](https://github.com/Azure/azure-storage-fuse/blob/09a7f54fc82476819849c742d3bc3f5f6204201e/README.md#environment-variables)

This AZURE_STORAGE_BLOB_ENDPOINT is needed when [using a blob from sovereign clouds]( https://github.com/Azure/azure-storage-fuse/wiki/2.-Configuring-and-Running#sovereign-clouds
).

**What you expected to happen**:
allow user to specify the blob endpoint, and the value should be set as AZURE_STORAGE_BLOB_ENDPOINT env variable before calling blobfuse

**Describe the solution you'd like in detail**

**Describe alternatives you've considered**

**Additional context**

Unable to use these drivers in mooncake region.

**Comment by andyzhangx** [comment]
blobfuse v1.1.1 already supports customized AZURE_STORAGE_BLOB_ENDPOINT:
https://github.com/Azure/azure-storage-fuse/blob/v1.1.1/blobfuse/blobfuse.cpp#L79
I would work out a new flexvol driver to support customized AZURE_STORAGE_BLOB_ENDPOINT
Point is we need to write a k8s daemonset to upgrade the built-in (blobfuse v1.0.3) to latest blobfuse v1.1.1

**Comment by andyzhangx** [comment]
fixed by https://github.com/Azure/kubernetes-volume-drivers/pull/42

**Comment by andyzhangx** [comment]
It's better use `1.2.4` to support Azure China cloud
