### ISSUE TITLE
CSI driver for SMB

### ISSUE THREAD

**Issue by giggio** [Azure/kubernetes-volume-drivers#48]
**Is your feature request related to a problem? Please describe.**
Yes, we would like to use the new CSI driver.
As flexvolume [is deprecated](https://github.com/kubernetes/community/blob/master/sig-storage/volume-plugin-faq.md) we don't want to invest on it.

**Describe the solution you'd like in detail**
A CSI driver for smb.

**Describe alternatives you've considered**
Flexvolume, but it is deprecated.

**Comment by andyzhangx** [comment]
a new SMB CSI driver for on-premise and that does not provide dynamic provisioning?
there is already a new azure file CSI driver: https://github.com/kubernetes-sigs/azurefile-csi-driver

**Comment by giggio** [comment]
Exactly, for on premises.

**Comment by andyzhangx** [comment]
the functionality is actually  subset of https://github.com/kubernetes-sigs/azurefile-csi-driver since it won't need dynamic provisioning, I am planning to create a new project, e.g. `smb-csi-driver`, put it under https://github.com/kubernetes-sigs/ finally. 
The CSI driver https://github.com/kubernetes-sigs/smb-csi-driver would work on both linux and windows node, and it only provides static provisioning(user should bring their own SMB server address).
Is that ok?

**Comment by giggio** [comment]
Yes, that is ok!

**Comment by Dhiraj240** [comment]
@giggio @andyzhangx I would like to work this summer on this project. May I know how to start it.
Can you assign me an issue? also, during further days I would contribute and in that do I need to ask on the issues to get it assigned and then work.

**Comment by andyzhangx** [comment]
@Dhiraj240 thanks, I will create a new project first. Most of the project code in https://github.com/kubernetes-sigs/azurefile-csi-driver would be in https://github.com/kubernetes-sigs/smb-csi-driver.
In the meantime, would you pick up some work items first to warm up? thanks
https://github.com/kubernetes-sigs/azurefile-csi-driver/labels/help%20wanted

just ping my slack: andyzhang @kubernetes if you have any questions, thanks.

**Comment by Dhiraj240** [comment]
@andyzhangx Alright I will pick up randomly and try to submit PR once I build project on my local system.
Will ping you in slack for all things now.
Thanks.

**Comment by Dhiraj240** [comment]
Also, May I know for CSI driver project @ZeroMagic is again going to participate

**Comment by andyzhangx** [comment]
Update: here is the initial working SMB CSI driver: 
https://github.com/csi-driver/csi-driver-smb
Will migrate to https://github.com/kubernetes-csi/csi-driver-smb after a while

**Comment by giggio** [comment]
It looks like we have a release. We'll try it out. https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v0.1.0

**Comment by andyzhangx** [comment]
> It looks like we have a release. We'll try it out. https://github.com/kubernetes-csi/csi-driver-smb/releases/tag/v0.1.0

really fresh release... I am trying to set up the e2e test pipeline on that project.

**Comment by andyzhangx** [comment]
SMB CSI driver is already GA
