### ISSUE TITLE
container not starting, error in kubelet "Failed to mount device /dev"

### ISSUE THREAD

**Issue by playersons** [Azure/kubernetes-volume-drivers#59]
**What happened**:
Pod is not starting up, I am seeing errors as below:

on the node /var/log/blobfuse-driver.log :
```
Thu Jun 11 08:06:32 UTC 2020 INFO: tmp-path not specified, use default path: /tmp/blobfuse/
Thu Jun 11 08:06:32 UTC 2020 EXEC: mkdir -p /var/lib/kubelet/pods/56e9105e-06fb-4a8a-8b1b-57b3ba7f8687/volumes/azure~blobfuse/pv-blobfuse-flexvol
Thu Jun 11 08:06:32 UTC 2020 INF: AZURE_STORAGE_SAS_TOKEN is set
Thu Jun 11 08:06:32 UTC 2020 INF: export storage account - export AZURE_STORAGE_ACCOUNT=azeuwstotestingkuber01
Thu Jun 11 08:06:32 UTC 2020 EXEC: blobfuse /var/lib/kubelet/pods/56e9105e-06fb-4a8a-8b1b-57b3ba7f8687/volumes/azure~blobfuse/pv-blobfuse-flexvol --container-name=azeuwstotestingkuber01 --tmp-path=/tmp/blobfuse/ -o allow_other
Thu Jun 11 08:06:32 UTC 2020 ERROR: { "status": "Failure", "message": "Failed to mount device /dev/ at /var/lib/kubelet/pods/56e9105e-06fb-4a8a-8b1b-57b3ba7f8687/volumes/azure~blobfuse/pv-blobfuse-flexvol, accountname:azeuwstotestingkuber01, error log:Thu Jun 11 08:06:32 UTC 2020 EXEC: blobfuse /var/lib/kubelet/pods/56e9105e-06fb-4a8a-8b1b-57b3ba7f8687/volumes/azure~blobfuse/pv-blobfuse-flexvol --container-name=azeuwstotestingkuber01 --tmp-path=/tmp/blobfuse/ -o allow_other " }
```
kubectl describe show this output:
```
Events:
  Type     Reason       Age               From                                       Message
  ----     ------       ----              ----                                       -------
  Normal   Scheduled    <unknown>         default-scheduler                          Successfully assigned default/nginx-flex-blobfuse to aks-prodnode-29454676-vmss000001
  Warning  FailedMount  3s (x5 over 11s)  kubelet, aks-prodnode-29454676-vmss000001  MountVolume.SetUp failed for volume "pv-blobfuse-flexvol" : invalid character 'F' looking for beginning of value
```
In my case, too, /tmp/blobfuse did not exist and I created it manually on all nodes.

PV and PVC are created as required:
```
NAME                  CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                          STORAGECLASS   REASON   AGE
pv-blobfuse-flexvol   100Gi      RWX            Retain           Bound    default/pvc-blobfuse-flexvol                           50m
NAME                   STATUS   VOLUME                CAPACITY   ACCESS MODES   STORAGECLASS   AGE
pvc-blobfuse-flexvol   Bound    pv-blobfuse-flexvol   100Gi      RWX                           50m
```
**What you expected to happen**:

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.16.9
- OS (e.g. from /etc/os-release): Ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0-1083-azure
- Install tools:
- Others: blobfuse version 1.2.3

**Comment by andyzhangx** [comment]
same issue as https://github.com/Azure/kubernetes-volume-drivers/issues/58

**Comment by playersons** [comment]
Except for the fact, that the reporter of issue #58 was able to get it working. In my case, creating the host volume did not help.

**Comment by andyzhangx** [comment]
I would suggest use https://github.com/kubernetes-sigs/blobfuse-csi-driver, this flexvolume driver is now in maintenance mode since we are switching to csi driver.

**Comment by playersons** [comment]
I'd love to do that but I've read that the status for the csi driver is beta. Do you have any timeline for this to change? We have policies in place that keep us from using beta flagged software.

**Comment by andyzhangx** [comment]
> I'd love to do that but I've read that the status for the csi driver is beta. Do you have any timeline for this to change? We have policies in place that keep us from using beta flagged software.

GA time for blobfuse CSI driver could be late this year.
For this flexvolume issue, follow troubleshooting tips here: https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse#tips

**Comment by playersons** [comment]
after rebuild from scratch, driver is working as expected. can’t reproduce error any more. must have been something odd on the first try.
