### ISSUE TITLE
Where is the Dockerfile for "andyzhangx/local-volume-provisioner" please

### ISSUE THREAD

**Issue by rbtcollins** [Azure/kubernetes-volume-drivers#62]
**What happened**:

Wanted to built a custom image to test different cleaner configurations, and realised that there doesn't seem to be a repository / dockerfile for the image for the local static provisioner image.

**What you expected to happen**:

There should be a published source repository for the image. None is listed https://hub.docker.com/r/andyzhangx/local-volume-provisioner either.

**How to reproduce it**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
use master branch should be ok since it has the key PR: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/187, you could find Dockerfile here: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner, run following command to build a container:
```
make provisioner
```

I will make up a new image under `mcr.microsoft.com` later, thanks for remindar.

**Comment by andyzhangx** [comment]
it's done, try latest yaml files, thanks.

**Comment by rbtcollins** [comment]
thank you

**Comment by rbtcollins** [comment]
FYI this is the thing I wanted to fix - https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/200; 15 seconds or so to discard a 210G partition on a L8sv2 VM, vs 20m or more with the shred example in your example https://github.com/Azure/kubernetes-volume-drivers/blob/master/local/local-pv-provisioner-nvmedisk.yaml

**Comment by andyzhangx** [comment]
thanks, I have updated image `mcr.microsoft.com/k8s/local-volume-provisioner:v2.3.5-alpha` with latest master branch(including your PR)
