### ISSUE TITLE
how to solve: single storageaccount/single container/multiple pods in multiple namespaces

### ISSUE THREAD

**Issue by playersons** [Azure/kubernetes-volume-drivers#65]
I am trying to get multiple pods (different services) in two different namespaces to use the same storage account and storage container. So far, no luck. The first PV, PVC and Pod is starting fine, no problem. But I can't handle the second one. To my understanding, I have to use one or more PVC bound to a single PV, but this does not work over namespaces, right?
When I try to add a second PV and also a second PVC in the second namespace, I can't get the volume to mount, the Pod won't start. I assume, the flexvolume driver can't use the same storage account and storage container in multiple PV relations. Is this correct?
If so, is there any workaround to use a single storage container multiple namespaces/Pods?

**Environment**:
- Kubernetes version: 1.16.9
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`): 4.15.0
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I would suggest switch to use blobfuse csi driver, it should work well: https://github.com/kubernetes-sigs/blobfuse-csi-driver/blob/master/deploy/example/storageclass-blobfuse-csi-existing-container.yaml

**Comment by playersons** [comment]
I could work around the mount issue by connecting each pod directly with the flexvolume driver instead of using pv/pvc method.
Now I am wondering, if I‘ll run into other issuess when multiple pods (from one replica set) will use the same `tmppath`.
I really would like to avoid putting each pod in its own replica set, but am unsure if sharing a tmppath is possible at all.

Thank you for your valued efforts.

**Comment by andyzhangx** [comment]
you should not share the tmppath for two pods on the same node, it would have conflict. I think use two separate PV/PVCs should work.  What's your config and error message?

Also I would suggest switch to use blobfuse csi driver, it could support deployment, statefulset, here is an example: https://github.com/kubernetes-sigs/blobfuse-csi-driver/blob/master/deploy/example/statefulset.yaml

**Comment by playersons** [comment]
Thank you for your reply. So, basically I would have to have multiple PV per storageaccount/container and would assign each pod its own PVC to access blobfuse, right? This means I can’t avoid to have a replicaCount of 1 per deployment/replicaSet, right?

**Comment by andyzhangx** [comment]
You could use PV1/PVC1, PV2/PVC2, and PV1 & PV2 use same storage account/container, that should work

**Comment by playersons** [comment]
Thank you for your sharing, one last question, though. Would you prefer PV/PVC or direct Pod-flexvolume connection, I am unsure about pros and cons for both methods here.

**Comment by andyzhangx** [comment]
depends on your usage, direct Pod-flexvolume connection is more easier to configure, while if you want to use one PVC in multiple pods, you should use PV/PVC.
