### ISSUE TITLE
Pods which mounted to the same Azure-Blob(using flex volume) can not run on the same node

### ISSUE THREAD

**Issue by Binyang2014** [Azure/kubernetes-volume-drivers#66]
**What happened**:

Using blob flex volume. Create PV and PVC for the blob storage. When two pod using same PVC scheduled to the same node. One pod will mount blob storage successfully, another will failed. Error is: `Error: temp directory '/tmp/blobfuse' is not empty. blobfuse needs an empty temp directory`.
I think it caused by blob flex volume using the same `temp dir` for all pods.

**What you expected to happen**:
No error occur.

**How to reproduce it**:
1. Using blob flex volume. Create PV, PVC. 
2. Create one pod and let it using blob PVC.
3. Create another pod, let it using blob PVC and schedule it  the same node as previous pod.
4. The second created pod will hang and failed to mount blob storage

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
could you use different `tmppath` on different PV? what's your flex volume driver version, is it on 1.0.13?

**Comment by Binyang2014** [comment]
We use flex volume which is version  is 1.0.11. But master branch seems still has this issue. https://github.com/Azure/kubernetes-volume-drivers/blob/3f77fd816170083b2575af5858eb3b47368c7f65/flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse#L58

Sure, we can use different `tmppath` on different PV.  But we don't want to create a new PV for each Pod.  If two pods consume the same PV (using same azure blob), they will encounter this problem.

**Comment by andyzhangx** [comment]
This issue should be by design on blobfuse v1.2.3, pls clean up `tmppath` in initContainer first or specify a non-existing `tmppath`, blobfuse flexvolume driver would make  tmppath for user.

```console
# blobfuse blob --container-name=test --tmp-path=/tmp/blobfuse/
Error: temp directory '/tmp/blobfuse' is not empty. blobfuse needs an empty temp directory
```

**Comment by andyzhangx** [comment]
> We use flex volume which is version is 1.0.11. But master branch seems still has this issue.
> 
> https://github.com/Azure/kubernetes-volume-drivers/blob/3f77fd816170083b2575af5858eb3b47368c7f65/flexvolume/blobfuse/deployment/blobfuse-flexvol-installer/blobfuse#L58
> 
> Sure, we can use different `tmppath` on different PV. But we don't want to create a new PV for each Pod. If two pods consume the same PV (using same azure blob), they will encounter this problem.

if two pods are scheduled on same node, then it may have same issue. This is a restraint of current blobfuse flexvolume driver, we suggest user to use blobfuse CSI driver instead:  https://github.com/kubernetes-sigs/blobfuse-csi-driver

**Comment by Binyang2014** [comment]
> if two pods are scheduled on same node, then it may have same issue. This is a restraint of current blobfuse flexvolume driver, we suggest user to use blobfuse CSI driver instead: https://github.com/kubernetes-sigs/blobfuse-csi-driver

Thanks for reply, I want to know if blobfuse flexvolume will be deprecated in future? And want's the official suggestion about blobfuse flexvolume and blobfuse CSI.  Do we recommend to use blobfuse CSI instead of flexvolume?

**Comment by andyzhangx** [comment]
This blobfuse flexvolume is in maintenance mode now, we suggest using blobfuse CSI driver instead: https://github.com/kubernetes-sigs/blobfuse-csi-driver

**Comment by andyzhangx** [comment]
For this issue, there is another workaround, downgrade blobfuse on every agent node to 1.1.1, following command will run a daemonset on every agent node to downgrade blobfuse to 1.1.1
```console
kubectl apply -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/blobfuse/binary/sysctl-install-blobfuse-1.1.1.yaml
```

After daemonset is running on every agent node, you will see the version is downgraded to `1.0.3`(it's a version display bug in 1.1.1, actually it's really `1.1.1`)
```
# kubectl-enter aks-nodepool1-33433896-0
/# blobfuse --version
blobfuse 1.0.3
```
