### ISSUE TITLE
Fail to discover NVMe disks

### ISSUE THREAD

**Issue by ams0** [Azure/kubernetes-volume-drivers#75]
**What happened**:

Following https://github.com/Azure/kubernetes-volume-drivers/tree/master/local on a cluster with a 1-node Standard_Lv8s_v2 node, it fails to detect the nvme disk:

```
E0824 14:27:00.945914       1 discovery.go:220] Failed to discover local volumes: 1 error(s) while discovering volumes: [Skipping file "/dev/nvme0": not a directory nor block device]
```

I'm able to format and mount `/dev/nvme0n1` directly on the node

```
root@aks-nvme-31968050-vmss000000:/# mkfs.ext4 /dev/nvme0n1
mke2fs 1.42.13 (17-May-2015)
Discarding device blocks: done
Creating filesystem with 468843606 4k blocks and 117211136 inodes
Filesystem UUID: 89667bcc-a69e-4574-b8bf-0096b0099fb8
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
        4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968,
        102400000, 214990848

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done

root@aks-nvme-31968050-vmss000000:/# mount /dev/nvme0n1 /mnt/
root@aks-nvme-31968050-vmss000000:/# ls /mnt
lost+found
```

Also, I had to create the `fast-disks` StorageClass before applying the [manifest for NVMe](https://github.com/Azure/kubernetes-volume-drivers/blob/master/local/local-pv-provisioner-nvmedisk.yaml), so perhaps the doc needs to be fixed too. 

**What you expected to happen**:

NVMe disks at `/dev/nvme0` to be discovered and available to local provisioner.

**How to reproduce it**:

Create an AKS cluster (tried 1.16.3 and 1.18.6), add a nodepool with size `Standard_Lv8s_v2` and apply the manifest for NVMe.

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.18.6 and 1.16.3
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

cc @andyzhangx

**Comment by andyzhangx** [comment]
the error said `Skipping file "/dev/nvme0": not a directory nor block device`, so have you already formatted `/dev/nvme0` before running `kubectl apply -f https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/local/local-pv-provisioner-nvmedisk.yaml` ?

**Comment by andyzhangx** [comment]
wait, `/dev/nvme0n1` should be discovered successfully, right? Since it's using `namePattern: nvme*`
https://github.com/Azure/kubernetes-volume-drivers/blob/4f7291abbec1984ec0f346f9d6f85fdfddfa38e8/local/local-pv-provisioner-nvmedisk.yaml#L18

**Comment by ams0** [comment]
My bad, I thought the local provisioned would take care of the formatting (I read that it can form a RAID with multiple nvme devices). My goal is to avoid using a Daemonset to format the disk or worse accessing the node directly. Do you know if it’s possible, to have the nvme disk formatted? Thanks for the super quick reply!

**Comment by andyzhangx** [comment]
The solution here(https://github.com/Azure/kubernetes-volume-drivers/tree/master/local) would leverage [sig-storage-local-static-provisioner](https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner) running as a DaemonSet to discover and format nvme disk, it won't configure RAID, would create one PV per disk. That's the way how it works, if we don't use a daemonset to format a disk, how can we do the format, the format should happen on the node, right?

**Comment by ams0** [comment]
Indeed, you're right, some mechanism must format the disk before being used by the local volume driver. I just thought that perhaps some of the scripts here: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/tree/78a6f6e547099939019fec41c77d2727cd5e6f5e/deployment/docker/scripts could format the device before using it, or it's a functionality that can be added to `mcr.microsoft.com/k8s/local-volume-provisioner` (can't find the Dockerfile for that anywhere, by the way)?

**Comment by ams0** [comment]
I created this issue to have `nvme-cli` installed on the base images in AKS: https://github.com/Azure/AKS/issues/1818 and made this repo to prepare the disks for use: https://github.com/ams0/aks-nvme-ssd-provisioner

**Comment by andyzhangx** [comment]
@ams0 `mcr.microsoft.com/k8s/local-volume-provisioner:v2.3.5-alpha` is actually master branch build of https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner which contains https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner/pull/187, once sig-storage-local-static-provisioner published a new release, will use that image. So I would suggest use official sig-storage-local-static-provisioner image since it already have what you want, right? Currently you could just use image `mcr.microsoft.com/k8s/local-volume-provisioner:v2.3.5-alpha` or build image from sig-storage-local-static-provisioner by yourself?

**Comment by andyzhangx** [comment]
To fix the above error msg, if you could make sure you have only one NVMe disk, set `namePattern: nvme0*` in the config file, below is a sample output on `Standard_L16s_v2` which has two NVMe disks:

```
# ls /dev/nvme* -lt
brw-rw---- 1 root disk 259, 1 Aug 25 07:29 /dev/nvme1n1
brw-rw---- 1 root disk 259, 0 Aug 25 07:29 /dev/nvme0n1
crw------- 1 root root 243, 0 Aug 25 07:29 /dev/nvme0
crw------- 1 root root 243, 1 Aug 25 07:29 /dev/nvme1
```

**Comment by ams0** [comment]
I made this https://github.com/ams0/aks-nvme-ssd-provisioner/blob/master/manifests/storage-local-static-provisioner.yaml to use an `initContainer` to initialize the disks, so I'm happy :) thanks for your help, this can be closed.

**Comment by olsenme** [comment]
@ams0  would you be open to having a chat with the PG team to learn more about your use case?

**Comment by ams0** [comment]
@olsenme absolutely, ping me on Teams or on LinkedIn: https://www.linkedin.com/in/alessandrovozza
