### ISSUE TITLE
Same as issue #7 Mounting BlobStorage Shows `AccountName is empty`

### ISSUE THREAD

**Issue by xiaolul** [Azure/kubernetes-volume-drivers#77]
**What happened**:
Try to setup per instructions provided in the example, but got error 
` ERROR: {"status": "Failure", "message": "validation failed, error log:accountname is empty"}`

**What you expected to happen**:
The blob container mounts to the pod successfully.

**How to reproduce it**:
I follow exactly as the instruction detailed, blobfuse is installed. Credential is definitely provided.

**Anything else we need to know?**:
- Manually mount the container to a directory works.
- I've created the scerect exactly as the steps listed in the example.

**Environment**:
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
```
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```
- Kernel (e.g. `uname -a`): `Linux tokyo-dev-master00 5.0.0-36-generic #39~18.04.1-Ubuntu SMP Tue Nov 12 11:09:50 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools: apt

- Others:
Running `kubectl describe secret blobfusecreds` gives the right output:
```
 kubectl describe secret blobfusecreds
Name:         blobfusecreds
Namespace:    default
Labels:       <none>
Annotations:  <none>

Type:  azure/blobfuse

Data
====
accountkey:   88 bytes
accountname:  17 bytes
```

**Comment by andyzhangx** [comment]
it looks like you have not installed `jq` in your machine: `apt install jq -y`

**Comment by andyzhangx** [comment]
also we recommend using blob csi driver: https://github.com/kubernetes-sigs/blob-csi-driver

**Comment by xiaolul** [comment]
Thank you the jq is exactly the issue. I closed the issue.
