### ISSUE TITLE
Is ARM64 supported by this project?

### ISSUE THREAD

**Issue by Nwhouse** [Azure/kubernetes-volume-drivers#78]
**Is your feature request related to a problem? Please describe.**

**I am trying to mount a SMB share to my Raspberry PI cluster, I have been working on this for several weeks and was hoping this project would provide a solution.**

**Describe the solution you'd like in detail**

Would like to see ARM64 support

**Describe alternatives you've considered**

**Additional context**

**Comment by andyzhangx** [comment]
I are not sure, does `mount -t cifs ...` command work on ARM64?

**Comment by Nwhouse** [comment]
It does

**Comment by andyzhangx** [comment]
I don't have a ARM64 env, so if you could try on ARM64, and found any issue, just paste details here, thanks. And make sure `jq`, `cifs-utils` tools are installed on the agent node.

**Comment by thewilli** [comment]
.. it seems at least the Docker Image is only build for x86, right @andyzhangx?

This should be mentioned somewhere and you could consider providing a multi-arch Image.

**Comment by andyzhangx** [comment]
> .. it seems at least the Docker Image is only build for x86, right @andyzhangx?
> 
> This should be mentioned somewhere and you could consider providing a multi-arch Image.

We don't want to support ARM64 for this smb flexvol driver,  instead ARM64 is already supported in SMB CSI driver: https://github.com/kubernetes-csi/csi-driver-smb/pull/140#issuecomment-723960639
