### ISSUE TITLE
PV not created

### ISSUE THREAD

**Issue by ksauce** [Azure/kubernetes-volume-drivers#79]
I followed the steps to install local provisioner for K8s on AKS.  Using https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/local/local-pv-provisioner-tempdisk.yaml ,  I attempted to point to an attached data drive that is shown below but no PVs are created

Is there something I am missing to enable this?

NAME    HCTL        SIZE MOUNTPOINT            FSTYPE
sda     0:0:0:0     100G
|-sda1             99.9G /host
|-sda14               4M
`-sda15             106M /host/boot/efi
sdb     1:0:1:0      64G
`-sdb1               64G /host/mnt
sdc     3:0:0:0     500G
`-sdc1              500G /host/datadisks/disk1
sdd     3:0:0:1      10G
`-sdd1               10G /host/datadisks/disk2
sr0     5:0:0:0    1024M

Logs:
I0929 19:51:37.025594       1 common.go:344] StorageClass "fast-disks" configured with MountDir "/host/datadisks/disk1/testshare", HostDir "/ho
st/datadisks/disk1/testshare", VolumeMode "Filesystem", FsType "ext4", BlockCleanerCommand ["/scripts/shred.sh" "2"], NamePattern "test*"
I0929 19:51:37.025677       1 main.go:63] Loaded configuration: {StorageClassConfig:map[fast-disks:{HostDir:/host/datadisks/disk1/testshare Mou
ntDir:/host/datadisks/disk1/testshare BlockCleanerCommand:[/scripts/shred.sh 2] VolumeMode:Filesystem FsType:ext4 NamePattern:test*}] NodeLabel
sForPV:[] UseAlphaAPI:false UseJobForCleaning:false MinResyncPeriod:{Duration:5m0s} UseNodeNameOnly:false LabelsForPV:map[] SetPVOwnerRef:false
}
I0929 19:51:37.025706       1 main.go:64] Ready to run...
W0929 19:51:37.025719       1 main.go:73] MY_NAMESPACE environment variable not set, will be set to default.
W0929 19:51:37.025738       1 main.go:79] JOB_CONTAINER_IMAGE environment variable not set.
I0929 19:51:37.025907       1 common.go:407] Creating client using in-cluster config
I0929 19:51:37.093921       1 main.go:85] Starting controller
I0929 19:51:37.093960       1 main.go:101] Starting metrics server at :8080
I0929 19:51:37.094077       1 controller.go:47] Initializing volume cache
I0929 19:51:37.194590       1 controller.go:111] Controller started

**Comment by andyzhangx** [comment]
@ksauce `local-pv-provisioner-tempdisk.yaml` is only for temp disk, which is mounted at `/mnt`, if you want to use data disk, try https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv

**Comment by ksauce** [comment]
The instructions on that page dynamically create a single data disk resource and deploying multiple Pods doesn't work.  

I can attach data disks to my VMSS (temp disks are sdb but data disks sdc and mounted under: /host/datadisks/disk1, etc, manually create a PV for each node (using the nodeAffinity:), create the Storage class, PersistentVolumeClaim, and then deploy.  multiple replicas.  Now I can have these replicas mount the same volume if they end up on the same node

**Comment by andyzhangx** [comment]
there is a `namePattern` field, so only `sdb1` disk would be matched.
https://github.com/Azure/kubernetes-volume-drivers/blob/6de8b5322243e09ddcc78c65c96abaf60dc22587/local/local-pv-provisioner-tempdisk.yaml#L18

For azure data disk support, should follow up https://docs.microsoft.com/en-us/azure/aks/azure-disks-dynamic-pv, this local disk solution is only for local temp disk, has local disk limitations.

**Comment by ksauce** [comment]
Got it.  thank you
