### ISSUE TITLE
CSI support for Kubernetes v1.12.x

### ISSUE THREAD

**Issue by mattkelly** [Azure/kubernetes-volume-drivers#8]
The way CSIs are registered/operate has fundamentally changed in Kubernetes v1.12.x. This means that the existing images and manifests no longer work:

```
Events:
  Type     Reason                  Age               From                                              Message
  ----     ------                  ----              ----                                              -------
  Normal   Scheduled               27s               default-scheduler                                 Successfully assigned default/nginx-csi-hostpath to cs-3f10d2ba-bec9-4f75-92fc-bdd571e26633
  Normal   SuccessfulAttachVolume  27s               attachdetach-controller                           AttachVolume.Attach succeeded for volume "kubernetes-dynamic-pv-34d8871adbc411e8"
  Warning  FailedMount             3s (x6 over 19s)  kubelet, cs-3f10d2ba-bec9-4f75-92fc-bdd571e26633  MountVolume.MountDevice failed for volume "kubernetes-dynamic-pv-34d8871adbc411e8" : driver name csi-hostpath not found in the list of registered CSI drivers
```

You can easily reproduce this by following the steps listed [here](https://github.com/Azure/kubernetes-volume-drivers/tree/master/csi/hostpath).

Other CSIs broke in the same way. For example, you can reference the [similar DigitalOcean issue](https://github.com/digitalocean/csi-digitalocean/issues/86) that was [recently fixed](https://github.com/digitalocean/csi-digitalocean/pull/95) (though the issue itself is not closed yet).

**Comment by andyzhangx** [comment]
@mattkelly thanks for pointing out, I will fix it.

**Comment by mattkelly** [comment]
Thanks @andyzhangx! Any chance you can provide a rough ETA for a new image being pushed?

**Comment by andyzhangx** [comment]
@mattkelly It's not related to the csi-hostpath image, I have followed exactly as https://kubernetes-csi.github.io/docs/Example.html, and it works. There is really big change in v1.12.x, by default, CSI is even not enabled. Anyway, the csi-hostpath works now. And thanks for pointing out, my next major work would write azure disk & azure file csi drivers, make it work on v1.12.x

**Comment by andyzhangx** [comment]
close this issue since I have already implemented following csi drivers which supports k8s v1.12:
https://github.com/Azure/kubernetes-volume-drivers/tree/master/csi/azuredisk
https://github.com/Azure/kubernetes-volume-drivers/tree/master/csi/azurefile

**Comment by andyzhangx** [comment]
share you the new azure CSI drivers, it's under kubernetes-sig now:
https://github.com/kubernetes-sigs/azuredisk-csi-driver
https://github.com/kubernetes-sigs/azurefile-csi-driver

You could run those drivers on k8s v1.13.x
