### ISSUE TITLE
Unable to attach or mount volumes: unmounted volumes=[test], unattached volumes=[test default-token-l52vd]: failed to get Plugin from volumeSpec for volume "test" err=no volume plugin matched

### ISSUE THREAD

**Issue by esohailshaikh** [Azure/kubernetes-volume-drivers#80]
Hi 

We are currently planning to mount blob storage with AKS, before that we are trying to implement the same on minikube installed on Linux VM but not able to get it to work.

As mentioned in the documentation, I have followed the below steps:

1. Installed blobfuse driver on Linux VM
2. Installed blobfuse as a daemon set 
3. create a secret which stores Azure storage account name and account key
4. create a secret which stores Azure storage account name and account SAS token [command not working, as we already created the credentials with the same name, Skipped]
5. Created PV, PVC, and pod.
6. Installed SMB with the below command.
curl -skSL https://raw.githubusercontent.com/Azure/kubernetes-volume-drivers/master/flexvolume/smb/deployment/install-smb-flexvol-ubuntu.sh | sh -s --

After installing the SMB, the status is the same below is the error message.
  
```
Normal   Scheduled    14s               default-scheduler  Successfully assigned default/nginx-flex-blobfuse to liferaydockerization
  Warning  FailedMount  1s (x2 over 14s)  kubelet            Unable to attach or mount volumes: unmounted volumes=[test], unattached volumes=[test default-token-l52vd]: failed to get Plugin from volumeSpec for volume "test" err=no volume plugin matched
```

Thanks

**Comment by andyzhangx** [comment]
you are messing up blobfuse with smb, try this: https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse, and for blobfuse, it's suggested to use CSI driver: https://github.com/kubernetes-sigs/blob-csi-driver

**Comment by esohailshaikh** [comment]
OK.. understood to use Blobfluse, CSI driver is required. Still, the link which you have mentioned  "https://github.com/Azure/kubernetes-volume-drivers/tree/master/flexvolume/blobfuse", I have followed the same only the errors while running the pod is because of the CSI plugin right? ( Just want to be sure)
Can this be implemented on minikube?

Thank you for your amazing support.

**Comment by andyzhangx** [comment]
I am not sure whether it works on minikube

**Comment by andyzhangx** [comment]
as I know, SMB csi driver works on minikube, so blob csi driver could also work on minikube

**Comment by esohailshaikh** [comment]
Hi Andy

After running the below command to install CSI Drive getting the pod status as Error/Crashloopback  and pending
curl -skSL https://raw.githubusercontent.com/kubernetes-sigs/blob-csi-driver/v0.9.0/deploy/install-driver.sh | bash -s v0.9.0 --

`"Warning  FailedScheduling  29s (x2 over 29s)  default-scheduler  0/1 nodes are available: 1 node(s) didn't have free ports for the requested pod ports."`

  Normal   Created    2m22s                kubelet            Created container liveness-probe
  Normal   Started    2m22s                kubelet            Started container liveness-probe
  Normal   Pulled     96s (x4 over 2m22s)  kubelet            Container image "mcr.microsoft.com/k8s/csi/blob-csi:v0.9.0" already present on machine
  Normal   Created    96s (x4 over 2m22s)  kubelet            Created container blob
  Normal   Started    96s (x4 over 2m21s)  kubelet            Started container blob
  Warning  BackOff    93s (x7 over 2m20s)  kubelet            Back-off restarting failed container

**Comment by esohailshaikh** [comment]
![image](https://user-images.githubusercontent.com/70631439/94776644-b8ec0d00-03df-11eb-9926-a0c2e5d8b88a.png)

**Comment by andyzhangx** [comment]
Blob CSI driver needs azure credential file, make sure you have configured it correct: https://github.com/kubernetes-sigs/blob-csi-driver#prerequisite

Here is the way about how to troubleshooting the driver crash:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/docs/csi-debug.md#case1-volume-createdelete-issue
