### ISSUE TITLE
Blobfuse - tmp-path is not working as expected

### ISSUE THREAD

**Issue by supermario66** [Azure/kubernetes-volume-drivers#82]
The blobfuse driver is not taking the tmp-path which we are passing through yaml.

Logs:
tmp-path not specified, use default path: /tmp/blobfuse/

We don't see the blobfuse in the /tmp aswell.

**Comment by andyzhangx** [comment]
we don't map `/tmp` to host now, I think we should map `tmp-path` to `/mnt` by default since `/mnt` is quite fast, WDYT?

https://github.com/Azure/kubernetes-volume-drivers/blob/eab8929e6ae2060d3e16c369e6dce88938f85637/flexvolume/blobfuse/deployment/blobfuse-flexvol-installer-1.9.yaml#L27-L33

**Comment by bergerx** [comment]
I hope that won't create a conflict with
https://github.com/Azure/AKS/issues/1753.

**Comment by andyzhangx** [comment]
fixed by https://github.com/Azure/kubernetes-volume-drivers/issues/82

**Comment by andyzhangx** [comment]
this issue is fixed in `mcr.microsoft.com/k8s/flexvolume/blobfuse-flexvolume:1.0.14`
