### ISSUE TITLE
How to specify SPN or MSI for blobfuse FlexVolume

### ISSUE THREAD

**Issue by FrankCRoth** [Azure/kubernetes-volume-drivers#83]
Hi,

I would like to use authentication type SPN or MSI instead of SAS token or key like described here:
[Azure-Storage-Fuse Authentication Setup](https://github.com/Azure/azure-storage-fuse#valid-authentication-setups).

How would I specify it blobfusecreds secret configuration?

Regards,
Frank

**Comment by andyzhangx** [comment]
those auth types are only supported by csi driver: https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/storageclass-blobfuse-msi.yaml

**Comment by FrankCRoth** [comment]
Thx Andy. So it looks like MSI and SPN is supported. But how Do I configure this in blobfuse for FlexVolume? Could you give an example for SPN or MSI.

**Comment by andyzhangx** [comment]
MSI and SPN is only supported by CSI driver.

try install blob csi driver first: 
https://github.com/kubernetes-sigs/blob-csi-driver
and then use storage class:
https://github.com/kubernetes-sigs/blob-csi-driver/blob/master/deploy/example/storageclass-blobfuse-msi.yaml

**Comment by FrankCRoth** [comment]
Ok, thx. So I guess it would be a feature request. I will switch to CSI driver.

**Comment by andyzhangx** [comment]
blobfuse flexvol driver is in maintenance mode, we commend using CSI driver instead. Thanks.
