### ISSUE TITLE
MountVolume.SetUp failed

### ISSUE THREAD

**Issue by clomeli-ms** [Azure/kubernetes-volume-drivers#95]
**What happened**: I am trying to run blobfuse from a GKE cluster and my pod is notifying me that:

`  Warning  FailedMount       8s (x7 over 40s)     kubelet            MountVolume.SetUp failed for volume "4453dad8-ff00-4cf8-a48b-3d64687a56e9" : invalid character '/' looking for beginning of value` 

I have checked my /var/log/blobfuse-driver.log and it says:

`ENV Path: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
Tue Dec 1 00:26:26 UTC 2020 INFO: {"status": "Success", "capabilities": {"attach": false, "fsGroup": false}}
Tue Dec 1 00:58:50 UTC 2020 ERROR: {"status": "Failure", "message": "validation failed, error log:accountname is empty"}
Tue Dec 1 00:58:51 UTC 2020 ERROR: {"status": "Failure", "message": "validation failed, error log:accountname is empty"}
Tue Dec 1 00:58:52 UTC 2020 ERROR: {"status": "Failure", "message": "validation failed, error log:accountname is empty"}
Tue Dec 1 00:58:54 UTC 2020 ERROR: {"status": "Failure", "message": "validation failed, error log:accountname is empty"}
Tue Dec 1 00:58:58 UTC 2020 ERROR: {"status": "Failure", "message": "validation failed, error log:accountname is empty"}
...`

I also logged the input for the plugin and made sure that we are in fact passing in an accountname:

`{"container":"azureml-blobstore-ba186c2b-40db-4ea4-b766-b971484ddec8","kubernetes.io/fsType":"","kubernetes.io/pod.name":"job-gke-arc-test-1606857637-ce3283a0-nklqg","kubernetes.io/pod.namespace":"default","kubernetes.io/pod.uid":"b4ac1139-eb5a-42e2-a210-48eb06eec380","kubernetes.io/pvOrVolumeName":"4453dad8-ff00-4cf8-a48b-3d64687a56e9","kubernetes.io/readwrite":"rw","kubernetes.io/secret/accountkey":"ZTBheTNRL29icURCSzYxdWM2ZHZCdzUyd0JwUU1DRC9ycnZadFNHUklFeFhyRm9kRFZ3V2VsK3A0WkNiRWU1Um1seDdyS1V3bk5HVW5rWHZxRW5PMmc9PQ==","kubernetes.io/secret/accountname":"d3Myc3RvcmFnZTA3Mjg1ZGIyOWU5YTRj","kubernetes.io/serviceAccount.name":"default","mountoptions":"--file-cache-timeout-in-seconds=1000000","tmppath":"/tmp/4453dad8-ff00-4cf8-a48b-3d64687a56e9"}`

**What you expected to happen**:
The pod for this job was stuck in a qued state because of the mount failure. With a proper mounting it should work.

Let me know if you need anything else.

**Environment**:
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
- Kernel (e.g. `uname -a`):
Linux gke-cluster-1-default-pool-d6408dfc-d3m2 5.3.0-1036-gke #38-Ubuntu SMP Sun Sep 6 05:59:13 UTC 2020 x86_64 x86
_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by andyzhangx** [comment]
I think you did not install `jq` package on your agent node, on Ubuntu, run `apt install jq -y`
Does blobfuse work on GKE cluster? does it connect to Azure blob storage?

**Comment by clomeli-ms** [comment]
Oh yes thank you, I had used apt-get instead and didn't notice it did not install properly. And yes it does work on GKE!

**Comment by andyzhangx** [comment]
@clomeli-ms is your blobfuse driver connecting to Azure blob storage in GKE cluster? That's quite interesting scenario.
