### ISSUE TITLE
Unable to Mount a fileshare in AKS using SAS token

### ISSUE THREAD

**Issue by arthuersundar** [Azure/kubernetes-volume-drivers#96]
Hi Team,
We are unable to Mount a fileshare in AKS using SAS token. We are able to mount the same using access keys. 

it errors out throwing "couldn't extract azurestorageaccountname and azurestorageaccount key"

We used the below command to create the secret. Can you check.

kubectl create secret generic <<secretname>> --from-literal accountname=<<ACCOUNTNAME>>  --from-literal sasToken="<<SASURI>>"

**Comment by andyzhangx** [comment]
which driver and manual are you following?

**Comment by andyzhangx** [comment]
if it's azure file driver, you could follow: https://docs.microsoft.com/en-us/azure/aks/azure-files-dynamic-pv

**Comment by andyzhangx** [comment]
You must mount the Azure file share over SMB by using the storage account keys.
https://docs.microsoft.com/en-us/azure/storage/files/storage-files-faq#security-authentication-and-access-control
